let obstacles = []; // or classes?
let avatar = []; // or classes?
let overlapping = false;


// each of these will have x, y from 0 to 1 as generated by the poseLandmarker
let nosePosition = [];
let leftHandPosition = [];
let rightHandPosition = [];
let leftElbowPosition = [];
let rightElbowPosition = [];
let leftShoulderPosition = [];
let rightShoulderPosition = [];
let leftHipPosition = [];
let rightHipPosition = [];
let leftKneePosition = [];
let rightKneePosition = [];
let leftToePosition = [];
let rightToePosition = [];